notifications:
  email: false
git:
  quiet: true
  depth: false
language: node_js
node_js: lts/*
python: 3.7
os: linux
arch: amd64
addons:
  apt:
    update: true
    packages:
      - jq
      - curl
      - sudo
      - lsof
      - httpie
install: true
before_install:
  - export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 3000 5000 8080 5432
jobs:
  include:
    - stage: test
      name: css-correct-way-to-inline-blocks-with-flex
      env:
        - MY_PROJECT_NAME=css-correct-way-to-inline-blocks-with-flex
      before_script:
        - cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm i
        - cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm start
        - wait_for 1234
      script:
        - http :1234
        - http :1234/
      after_script: cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm stop
    - stage: test
      name: css-boxing-model-and-layout-basics
      env:
        - MY_PROJECT_NAME=css-boxing-model-and-layout-basics
      before_script:
        - cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm i
        - cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm start
        - wait_for 1234
      script:
        - http :1234
        - http :1234/
      after_script: cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm stop
    - stage: test
      name: frontender
      env:
        - MY_PROJECT_NAME=frontender
      before_script:
        - cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm i
        - cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm start
        - wait_for 1234
      script:
        - http :1234
        - http :1234/part1/index.html
      after_script: cd $TRAVIS_BUILD_DIR/$MY_PROJECT_NAME && npm stop
    - stage: test
      name: json-server-forever
      before_script:
        - cd $TRAVIS_BUILD_DIR/json-server-forever && npm i
        - cd $TRAVIS_BUILD_DIR/json-server-forever && npm start
        - wait_for 8080
      script:
        - http :8080/
        - http :8080/messages | jq '.'
        - http :8080/messages
        - http :8080/db.json
      after_script: cd $TRAVIS_BUILD_DIR/json-server-forever && npm stop
    - stage: test
      name: css-grid-display
      script:
        - cd $TRAVIS_BUILD_DIR/css-grid-display
        - npm i
        - npm run predeploy
    - stage: test
      name: css-grid-starter
      script:
        - cd $TRAVIS_BUILD_DIR/css-grid-starter
        - npm i
        - npm run predeploy
    - stage: test
      name: random-tachyons-button-styling
      script:
        - cd $TRAVIS_BUILD_DIR/random-tachyons-button-styling
        - npm i
        - npm run predeploy
    - stage: test
      name: parcel-starter
      script:
        - cd $TRAVIS_BUILD_DIR/parcel-starter
        - npm i
        - npm run predeploy
    - stage: test
      name: simple-starter
      script:
        - cd $TRAVIS_BUILD_DIR/simple-starter
        - npm i
        - npm run predeploy
    - stage: deploy
      name: GitHub pages deploy
      script: skip
      jdk: openjdk8
      env:
        - secure: Y72diIQXJV+Esi5Hkex7s9G5DrQ7GQdTXEKjFqWR1UlxV1JHpJwWNO9BqTp5rX3GjhdAGBgvjRNDDGVI706f+ZyULARhZF+i9eZQLzQOF0e+SxByxKmVwzPan9bkt1tdUT0PeSG8R4do5hkOar8+zzdRqjJqnEV1cLbmd7vvmvqULkE6Npy8fD0NrVEuFShue/IUXYDZdfzvq0KI1yv7YmMP8KwoU+f9Mk7Y7b6EVSleO5aU5bgfOlVAMWMSSx4ucqgmFnnE4+AYPNqRuxxZ5QqrKfzeEWOskCpc/KtKJfmHDS2A5DEIt+zLc2HzWyu+gvHzScw/GV+hN3VnuHn5M1hLSWA4MDb/AqN34jbVjZIIYybqs4dhOU+5DJdSnlH+PGIaq3YbdmgoajIs8n4iS42BymdObCB/TkLIfpmMa9RZ+UQWCEfNqf49Y8GKMkF/xvrKX3WTLrJNA4GOm0xJ7bTvsQCWuP5m9ru4SOI2o4zLFFAQACiWzpPIRitQH5IsPZep5EieUc0ounv4kQ0NEJkTvMUuXc9Je9wkgPVbrIoKmqr290DTvPif3RFed5urk4lR9WHu8KfBuKR0Y8f38TUxdpe8oWtyrCREk/J8GOUneSKfKnZT7uEirf2j6bJs9gaUrIg0tFpTnQGogHOTQ9Ju3g/jYIRDaz1tIFl8hn0=
      deploy: &pages
        provider: pages
        skip-cleanup: true
        keep-history: true
        target_branch: gh-pages
        github-token: "$GITHUB_TOKEN"
        on:
          branch: master

      #  local-dir: $TRAVIS_BUILD_DIR/target/generated-docs
      #before_deploy: cd $TRAVIS_BUILD_DIR && ./mvnw

      #  local-dir: $TRAVIS_BUILD_DIR/frontender/dist
      #before_deploy:
      #  - cd $TRAVIS_BUILD_DIR/frontender && npm i
      #  - cd $TRAVIS_BUILD_DIR/frontender && npm run predeploy

      #  local-dir: $TRAVIS_BUILD_DIR/css-boxing-model-and-layout-basics/dist
      #before_deploy:
      #  - cd $TRAVIS_BUILD_DIR/css-boxing-model-and-layout-basics && npm i
      #  - cd $TRAVIS_BUILD_DIR/css-boxing-model-and-layout-basics && npm run gh

        local-dir: $TRAVIS_BUILD_DIR/css-correct-way-to-inline-blocks-with-flex/dist
      before_deploy:
        - cd $TRAVIS_BUILD_DIR/css-correct-way-to-inline-blocks-with-flex && npm i
        - cd $TRAVIS_BUILD_DIR/css-correct-way-to-inline-blocks-with-flex && npm run gh
cache:
  directories:
  - ~/.m2
  - ~/.n*
  - ./*/node_modules
  - ~/.local/daggerok
